version: '3'

services:
  certbot:
    image: certbot/dns-cloudflare:latest
    volumes:
      - ./.docker/certbot/etc/:/etc/letsencrypt:rw
      - ./.docker/certbot/var/lib/letsencrypt:/var/lib/letsencrypt:rw